### ISSUE TITLE
整理歌手赛订票页面

### ISSUE THREAD

**Issue by BenjaminTanSF** [zgzgorg/yj.zgzg.io#103]
目前，页面正文只默认显示一个购票按钮，而大部分内容是被折叠在“常见问题”链接里的。我们没有必要让买票的人多点击一次才能得到问题的解答。将FAQ内容挪出，放到 pages/singerticket.md 里，as it should be

**Comment by tslmy** [comment]
@all-contributors please add @xubowenhaoren for code
